name: ShellGenie
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.7.0
  - anyio=4.8.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - charset-normalizer=3.4.1
  - click=8.1.8
  - colorama=0.4.6
  - cuda-cudart=12.8.90
  - cuda-cudart_win-64=12.8.90
  - cuda-nvrtc=12.8.93
  - cuda-version=12.8
  - diskcache=5.6.3
  - dnspython=2.7.0
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.2.2
  - fastapi=0.115.11
  - fastapi-cli=0.0.7
  - filelock=3.17.0
  - fsspec=2025.2.0
  - h11=0.14.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httptools=0.6.4
  - httpx=0.28.1
  - huggingface_hub=0.29.2
  - hyperframe=6.1.0
  - idna=3.10
  - intel-openmp=2024.2.1
  - jinja2=3.1.6
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.8.3.14
  - libffi=3.4.6
  - libhwloc=2.11.2
  - libiconv=1.18
  - liblapack=3.9.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libsqlite=3.49.1
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.6
  - libzlib=1.3.1
  - llama-cpp-python=0.2.24
  - llama.cpp=0.0.1660
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - mkl=2024.2.2
  - numpy=2.2.3
  - openssl=3.4.1
  - packaging=24.2
  - pip=25.0.1
  - prompt-toolkit=3.0.50
  - prompt_toolkit=3.0.50
  - pydantic=2.10.6
  - pydantic-core=2.27.2
  - pydantic-settings=2.8.1
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.10.11
  - python-dotenv=1.0.1
  - python-multipart=0.0.20
  - python_abi=3.10
  - pyyaml=6.0.2
  - requests=2.32.3
  - rich=13.9.4
  - rich-toolkit=0.11.3
  - setuptools=75.8.2
  - shellingham=1.5.4
  - sniffio=1.3.1
  - sse-starlette=2.2.1
  - starlette=0.46.0
  - starlette-context=0.3.6
  - tbb=2021.13.0
  - tk=8.6.13
  - tqdm=4.67.1
  - typer=0.15.2
  - typer-slim=0.15.2
  - typer-slim-standard=0.15.2
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - ucrt=10.0.22621.0
  - urllib3=2.2.1
  - uvicorn=0.34.0
  - uvicorn-standard=0.34.0
  - vc=14.3
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - watchfiles=1.0.4
  - wcwidth=0.2.13
  - websockets=15.0.1
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
